config/routes.rb
BuildingTrades::Application.routes.draw do
  

  devise_for :users, :skip => [:registrations] 
  resources :managers, only: [:index, :show]
  resources :custodians, only: [:index, :show]
  resources :companies, only: [:index, :show]
  resources :consultants, only: [:index, :show]
  resources :trades, only: [:index, :show]
  resources :plans, only: [:index, :show] do
    resources :contacts
  end


  devise_scope :user do
    root to: 'trades#index'
    #root to: 'passthrough#index' 
  end

  unauthenticated do
    root to: "sessions#new", :as => "unauthenticated"
  end

end

app/models/manager.rb
class Manager < ActiveRecord::Base
	has_many :accounts
	has_one :plan, through: :accounts
	has_many :asset_classes, through: :accounts

	def self.search(query)
  		where("man_name ilike ?", "%#{query}%") 
	end

	def total
		total = self.accounts.sum(:market_value)
	end

	def self.asset_class_find(asset_class_id)
		includes(:accounts).where('accounts.asset_class_id = ?', asset_class_id)
	end

end

app/controllers/managers_controller.rb
class ManagersController < ApplicationController
  before_action :set_manager, only: [:show, :edit, :update, :destroy]
  before_filter :authenticate_user!
  # GET /managers
  # GET /managers.json
 def index
    @asset_classes = AssetClass.all
    if params[:search]
      @managers = Manager.search(params[:search]).order("man_name ASC").paginate(page: params[:page], per_page: 10)
    else
      if params[:asset_class_id]
        @managers = Manager.asset_class_find(params[:asset_class_id]).order("man_name ASC").paginate(page: params[:page], per_page: 10)
        @assets = AssetClass.find(params[:asset_class_id])
      else
        @managers = Manager.order("man_name ASC").paginate(page: params[:page], per_page: 10)
      end
    end
  end


  # GET /managers/1
  # GET /managers/1.json
  def show
    total  = 0
    @manager.accounts.each do |ma|
      total += ma.market_value
    end
    respond_to do |format|
      format.html
      format.pdf do
        pdf = ManagerPdf.new(@manager, view_context, total)
        send_data pdf.render, type: "application/pdf", disposition: "inline"
      end
    end
  end

  # GET /managers/new
  def new
    @manager = Manager.new
  end

  # GET /managers/1/edit
  def edit
  end

  # POST /managers
  # POST /managers.json
  def create
    @manager = Manager.new(manager_params)

    respond_to do |format|
      if @manager.save
        format.html { redirect_to @manager, notice: 'Manager was successfully created.' }
        format.json { render action: 'show', status: :created, location: @manager }
      else
        format.html { render action: 'new' }
        format.json { render json: @manager.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /managers/1
  # PATCH/PUT /managers/1.json
  def update
    respond_to do |format|
      if @manager.update(manager_params)
        format.html { redirect_to @manager, notice: 'Manager was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @manager.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /managers/1
  # DELETE /managers/1.json
  def destroy
    @manager.destroy
    respond_to do |format|
      format.html { redirect_to managers_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_manager
      @manager = Manager.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def manager_params
      params.require(:manager).permit(:name)
    end
end

app/helpers/managers_helper.rb
module ManagersHelper
end

app/views/managers/_form.html.erb
<%= form_for(@manager, html: { class: 'form-horizontal' }) do |f| %>
  <%= f.error_notification %>
  
  <div class="form-inputs">
    <%= f.control_group :name do |f| %>
      <%= f.label :name, class: 'control-label' %>
      <div class="controls">
        <%= f.text_field :name %>
        <%= f.error_messages %>
      </div>
    <% end %>
  
  </div>
  
  <div class="form-actions">
    <%= f.submit class: 'btn btn-primary' %>
    <%= link_to "Cancel", managers_path, class: 'btn' %>
  </div>
<% end %>

app/views/managers/edit.html.erb
<% @title = "Editing manager" %>

<%= render 'form' %>

app/views/managers/index.html.erb
<% @title = "Managers" %>

<div style: 'text-align:left' class="btn-group">
  <%= dropdown_button "Asset Class" do %>
    <%= activatable_li_tag_with_link "All", managers_path %>
    <% @asset_classes.each do |asset_class| %>
      <%= activatable_li_tag_with_link "#{asset_class.name}", managers_path(asset_class_id: "#{asset_class.id}") %>
    <% end %>
  <% end %>
</div>

<%= form_tag(managers_path, :method => "get", id: "search-form", style: 'text-align:right') do %>
  <%= text_field_tag :search, params[:search], placeholder: "Search Managers", class: 'input-large search-query' %>
<%= button_tag(type: "submit", class: "btn btn-primary") do %>
   <i class="icon-search"></i> Search 
<% end %>
<% end %>



<div class="sheet sheet-condensed">
  <div class="sheet-inner">
    <table class="table">
      <thead>
        <tr>
          <th>Name</th>
          <th></th>
        </tr>
      </thead>
      <tbody>
      <% @managers.each do |manager| %>
        <tr>
          <td><i class="icon-plus-sign"> </i><%= manager.man_name %>
          <table style="display:none;" class="table">
            <thead>
              <tr>
                <th>Plan</th>
                <th>Asset Class</th>
                <th>Market Value</th>
              </tr>
            </thead>
            <tbody>
              <% iw_total = 0 %>
              <% smw_total = 0 %>
              <% manager.accounts.each do |ma| %>
                <% if ma.market_value? %>
                  <% if ma.plan.trade_id == 1 %>
                    <% iw_total = iw_total + ma.market_value %>
                  <% elsif ma.plan.trade_id == 2 %>
                    <% smw_total = smw_total + ma.market_value %>
                  <% end %>
                <% end %>
                <% if current_user.has_role? :iw %>
                  <% if ma.plan.trade_id == 1 %>
                    <tr>
                      <td>
                        <%= ma.plan.name %>
                      </td>
                      <td>
                        <%= ma.asset_class %>
                      </td>
                      <td>
                        <%= number_to_currency(ma.market_value)%>
                      </td>
                    <% end %>
                    </tr>
                <% elsif current_user.has_role? :smw %>
                  <% if ma.plan.trade_id == 2 %>
                    <tr>
                      <td>
                        <%= ma.plan.name %>
                      </td>
                      <td>
                        <%= ma.asset_class %>
                      </td>
                      <td>
                        <%= number_to_currency(ma.market_value)%>
                      </td>
                    <% end %>
                    </tr>
                <% else %>
                  <tr>
                      <td>
                        <%= ma.plan.name %>
                      </td>
                      <td>
                        <%= ma.asset_class %>
                      </td>
                      <td>
                        <%= number_to_currency(ma.market_value)%>
                      </td>
                    <% end %>
                    </tr>
                  <% end %>
                   <tr>
              <td>
              </td>
              <td>
                <strong>SMW Total:</strong>
              </td>
              <td>
                <strong><%= number_to_currency(smw_total) %></strong>
              </td>
            </tr>
             <tr>
              <td>
              </td>
              <td>
                <strong>IW Total:</strong>
              </td>
              <td>
                <strong><%= number_to_currency(iw_total) %></strong>
              </td>
            </tr>
            <tr>
              <td>
              </td>
              <td>
                <strong>Total:</strong>
              </td>
              <td>
                <strong><%= number_to_currency(smw_total + iw_total) %></strong>
              </td>
            </tr>
          </tbody>
        </table>
        </div></td>
          <td class="actions">
            <% if current_user.has_role? :all %>
              <%= link_to icon_tag("eye-open"), manager_path(manager, format: "pdf"), rel: 'tooltip', title: 'Show', target: "_blank" %>
            <% end %>
          </td>
        </tr>
      <% end %>
      </tbody>
    </table>
    <%= will_paginate @managers %>
  </div><!-- /.sheet-inner -->
</div><!-- /.sheet -->

app/views/managers/new.html.erb
<% @title = "New manager" %>

<%= render 'form' %>

app/views/managers/show.html.erb
<% @title = "Showing manager" %>

<div class="form-horizontal">
  <div class="control-group">
    <label class="control-label">Name</label>
    <div class="controls">
      <span class="uneditable-input span6"><%= @manager.name %></span>
    </div>
  </div>
  
  <div class="form-actions">
    <%= link_to icon_tag("pencil") + ' Edit', edit_manager_path(@manager), class: 'btn btn-primary' %>
    <%= link_to 'Back', managers_path, class: 'btn' %>
  </div>
</div>