config/routes.rb
BuildingTrades::Application.routes.draw do
  

  devise_for :users, :skip => [:registrations] 
  resources :managers, only: [:index, :show]
  resources :custodians, only: [:index, :show]
  resources :companies, only: [:index, :show]
  resources :consultants, only: [:index, :show]
  resources :trades, only: [:index, :show]
  resources :plans, only: [:index, :show] do
    resources :contacts
  end


  devise_scope :user do
    root to: 'trades#index'
    #root to: 'passthrough#index' 
  end

  unauthenticated do
    root to: "sessions#new", :as => "unauthenticated"
  end

end

app/models/company.rb
class Company < ActiveRecord::Base
	has_many :securities
	has_many :plans, through: :securities
	validates :cusip, uniqueness: true

	def self.search(query)
  		where("name ilike ?", "%#{query}%") 
	end


end

app/controllers/companies_controller.rb
class CompaniesController < ApplicationController
  before_action :set_company, only: [:show, :edit, :update, :destroy]
  before_filter :authenticate_user!
  # GET /companies
  # GET /companies.json
  def index
    if params[:search]
      @companies = Company.search(params[:search]).order("name ASC").paginate(page: params[:page], per_page: 10)
    else
      @companies = Company.order("name ASC").paginate(page: params[:page], per_page: 10)
    end
  end

  # GET /companies/1
  # GET /companies/1.json
  def show
    total  = 0
    @company.securities.each do |ma|
      total += ma.market_value
    end
    respond_to do |format|
      format.html
      format.pdf do
        pdf = CompanyPdf.new(@company, view_context, total)
        send_data pdf.render, type: "application/pdf", disposition: "inline"

      end
    end
  end

  # GET /companies/new
  def new
    @company = Company.new
  end

  # GET /companies/1/edit
  def edit
  end

  # POST /companies
  # POST /companies.json
  def create
    @company = Company.new(company_params)

    respond_to do |format|
      if @company.save
        format.html { redirect_to @company, notice: 'Company was successfully created.' }
        format.json { render action: 'show', status: :created, location: @company }
      else
        format.html { render action: 'new' }
        format.json { render json: @company.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /companies/1
  # PATCH/PUT /companies/1.json
  def update
    respond_to do |format|
      if @company.update(company_params)
        format.html { redirect_to @company, notice: 'Company was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @company.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /companies/1
  # DELETE /companies/1.json
  def destroy
    @company.destroy
    respond_to do |format|
      format.html { redirect_to companies_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_company
      @company = Company.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def company_params
      params[:company]
    end
end

app/helpers/companies_helper.rb
module CompaniesHelper
end

app/views/companies/_form.html.erb
<%= form_for(@company, html: { class: 'form-horizontal' }) do |f| %>
  <%= f.error_notification %>
  
  <div class="form-inputs">
  </div>
  
  <div class="form-actions">
    <%= f.submit class: 'btn btn-primary' %>
    <%= link_to "Cancel", companies_path, class: 'btn' %>
  </div>
<% end %>

app/views/companies/edit.html.erb
<% @title = "Editing company" %>

<%= render 'form' %>

app/views/companies/index.html.erb
<% @title = "Securities" %>

<%= form_tag(companies_path, :method => "get", id: "search-form", style: 'text-align:right') do %>
  <%= text_field_tag :search, params[:search], placeholder: "Search Securities", class: 'input-large search-query' %>
<%= button_tag(type: "submit", class: "btn btn-primary") do %>
   <i class="icon-search"></i> Search 
<% end %>
<% end %>

<div class="sheet sheet-condensed">
  <div class="sheet-inner">
    <%= will_paginate @companies %>
    <table class="table table-striped">
      <thead>
        <tr>
          <th>Company</th>
          <th>CUSIP/SEDOL</th>
          <th>Ticker</th>
        </tr>
      </thead>
      <tbody>
      <% @companies.order("name asc").each do |company| %>
        <tr>
          <td><i class="icon-plus-sign"> </i><%= company.name %> 

        <div style="display:none;"> 
          <table class="table">
          <thead>
            <tr>
              <th>Plan Name</th>
              <th>Manager Name</th>
              <th>Shares</th>
              <th>Market Value</th>
            </tr>
          </thead> 
          <tbody>
            <% iw_total = 0 %>
            <% smw_total = 0 %>
            <% company.securities.current.order("name asc").each do |spm| %>
            <% if spm.market_value? %>
              <% if spm.account.plan.trade_id == 1 %>
                <% iw_total = iw_total + spm.market_value %>
              <% elsif spm.account.plan.trade_id == 2 %>
                <% smw_total = smw_total + spm.market_value %>
              <% end %>
            <% end %>
            <% if current_user.has_role? :iw %>
              <% if spm.account.plan.trade_id == 1 %>
                <tr>
                  <td>
                  <%= spm.account.plan.name %>
                  </td>
                  <td>
                    <%= spm.account.manager.man_name%>
                  </td>
                  <td>
                    <%= spm.shares %>
                  <td>
                   <%= number_to_currency(spm.market_value) %>
                  </td>
                </tr>
              <% end %>
            <% elsif current_user.has_role? :smw %>
              <% if spm.account.plan.trade_id == 2 %>
                <tr>
                  <td>
                  <%= spm.account.plan.name %>
                  </td>
                  <td>
                    <%= spm.account.manager.man_name%>
                  </td>
                  <td>
                    <%= spm.shares %>
                  <td>
                   <%= number_to_currency(spm.market_value) %>
                  </td>
                </tr>
              <% end %>
             <% else %>   
              <tr>
                  <td>
                  <%= spm.account.plan.name %>
                  </td>
                  <td>
                    <%= spm.account.manager.man_name%>
                  </td>
                  <td>
                    <%= spm.shares %>
                  <td>
                   <%= number_to_currency(spm.market_value) %>
                  </td>
                </tr>
          <% end %>
          <tr>
             <% end %>
             <td>
              </td>
               <td>
              </td>
            <td>
                <strong>SMW Total:</strong>
              </td>
              <td>
                <strong><%= number_to_currency(smw_total) %></strong>
              </td>
            </tr>
             <tr>
               <td>
              </td>
              <td>
              </td>
              <td>
                <strong>IW Total:</strong>
              </td>
              <td>
                <strong><%= number_to_currency(iw_total) %></strong>
              </td>
            </tr>
            <tr>
               <td>
              </td>
              <td>
              </td>
              <td>
                <strong>Total:</strong>
              </td>
              <td>
                <strong><%= number_to_currency(smw_total + iw_total) %></strong>
              </td>
            </tr>
        </tbody>
      </table>
    </div></td>
        <td><%= company.cusip %></td>
        <td><%= company.ticker %></td>
          <td class="actions">
            <% if current_user.has_role? :all %>
              <%= link_to icon_tag("eye-open"), company_path(company, format: "pdf"), rel: 'tooltip', title: 'Show', target: "_blank" %>
              <% end %> 
          </td>
        </tr>
      <% end %>
      </tbody>

    </table>
    <%= will_paginate @companies %>
  </div><!-- /.sheet-inner -->
</div><!-- /.sheet -->

app/views/companies/new.html.erb
<% @title = "New company" %>

<%= render 'form' %>

app/views/companies/show.html.erb
<% @title = "Showing company" %>

<div class="form-horizontal">
  <div class="form-actions">
    <%= link_to icon_tag("pencil") + ' Edit', edit_company_path(@company), class: 'btn btn-primary' %>
    <%= link_to 'Back', companies_path, class: 'btn' %>
  </div>
</div>