config/routes.rb
BuildingTrades::Application.routes.draw do
  

  devise_for :users, :skip => [:registrations] 
  resources :managers, only: [:index, :show]
  resources :custodians, only: [:index, :show]
  resources :companies, only: [:index, :show]
  resources :consultants, only: [:index, :show]
  resources :trades, only: [:index, :show]
  resources :plans, only: [:index, :show] do
    resources :contacts
  end


  devise_scope :user do
    root to: 'trades#index'
    #root to: 'passthrough#index' 
  end

  unauthenticated do
    root to: "sessions#new", :as => "unauthenticated"
  end

end

app/models/plan.rb
class Plan < ActiveRecord::Base
	has_many :accounts


	def self.search(query)
  		where("name ilike ?", "%#{query}%") 
	end

	def total
		total = self.accounts.sum(:market_value)
	end


end

app/controllers/plans_controller.rb
class PlansController < ApplicationController
  before_action :set_plan, only: [:show, :edit, :update, :destroy]
  before_filter :authenticate_user!
  # GET /plans
  # GET /plans.json


  def index

    if current_user.has_role? :smw
      if params[:search]
        @plans = Plan.search(params[:search]).where("trade_id=2").order("name ASC").paginate(page: params[:page], per_page: 10)
      else
        @plans = Plan.where("trade_id=2").order("name ASC").paginate(page: params[:page], per_page: 10)
      end
    elsif current_user.has_role? :iw
      if params[:search]
        @plans = Plan.search(params[:search]).where("trade_id=1").order("name ASC").paginate(page: params[:page], per_page: 10)
      else
        @plans = Plan.where("trade_id=1").order("name ASC").paginate(page: params[:page], per_page: 10)
      end
    else
      if params[:search]
        @plans = Plan.search(params[:search]).order("name ASC").paginate(page: params[:page], per_page: 10)
      else
        @plans = Plan.order("name ASC").paginate(page: params[:page], per_page: 10)
      end
    end
  end

  # GET /plans/1
  # GET /plans/1.json
  def show
    respond_to do |format|
      format.html
      format.pdf do
        pdf = PlanPdf.new(@plan, view_context)
        send_data pdf.render, type: "application/pdf", disposition: "inline"

      end
    end
  end

  # GET /plans/new
  def new
    @plan = Plan.new
  end

  # GET /plans/1/edit
  def edit
  end

  # POST /plans
  # POST /plans.json
  def create
    @plan = Plan.new(plan_params)

    respond_to do |format|
      if @plan.save
        format.html { redirect_to @plan, notice: 'Plan was successfully created.' }
        format.json { render action: 'show', status: :created, location: @plan }
      else
        format.html { render action: 'new' }
        format.json { render json: @plan.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /plans/1
  # PATCH/PUT /plans/1.json
  def update
    respond_to do |format|
      if @plan.update(plan_params)
        format.html { redirect_to @plan, notice: 'Plan was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @plan.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /plans/1
  # DELETE /plans/1.json
  def destroy
    @plan.destroy
    respond_to do |format|
      format.html { redirect_to plans_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_plan
      @plan = Plan.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def plan_params
      params.require(:plan).permit(:name)
    end
end

app/helpers/plans_helper.rb
module PlansHelper
end

app/views/plans/_form.html.erb
<%= form_for(@plan, html: { class: 'form-horizontal' }) do |f| %>
  <%= f.error_notification %>
  
  <div class="form-inputs">
    <%= f.control_group :name do |f| %>
      <%= f.label :name, class: 'control-label' %>
      <div class="controls">
        <%= f.text_field :name %>
        <%= f.error_messages %>
      </div>
    <% end %>
  
  </div>
  
  <div class="form-actions">
    <%= f.submit class: 'btn btn-primary' %>
    <%= link_to "Cancel", plans_path, class: 'btn' %>
  </div>
<% end %>

app/views/plans/edit.html.erb
<% @title = "Editing plan" %>

<%= render 'form' %>

app/views/plans/index.html.erb
<% @title = "Plans" %>

<%= form_tag(plans_path, :method => "get", id: "search-form", style: 'text-align:right') do %>
  <%= text_field_tag :search, params[:search], placeholder: "Search Plans", class: 'input-large search-query' %>
<%= button_tag(type: "submit", class: "btn btn-primary") do %>
   <i class="icon-search"></i> Search 
<% end %>
<% end %>

<div class="sheet sheet-condensed">
  <div class="sheet-inner">
    <table class="table table-striped">
      <thead>
        <tr>
          <th>Plan Name</th>
          <th>Last Update</th>
        </tr>
      </thead>
      <tbody>
      <% @plans.each do |plan| %>
        <tr>
          <td><i class="icon-plus-sign"> </i><%= plan.name %>
        <table style="display:none;" class="table">
          <thead>
            <tr>
              <th>Manager</th>
              <th>Committed ($millions)</th>
              <th>Asset Class</th>
              <th>Market Value</th>
            </tr>
          </thead>
        <tbody>
          <% total = 0 %>
          <%plan.accounts.order("name asc").each do |pm| %>
          <tr>
            <td>
            <%= pm.name %>
          </td>
          <td>
            <% unless pm.committed.eql? "NULL" %>
              <%= pm.committed %>
            <% end %>
          </td>
          <td>
            <%= pm.asset_class %>
          </td>
          <td>
            <%= number_to_currency(pm.market_value)%>
          </td>
        </tr>
        <% end %>
        <tr>
          <td>
          </td>
          <td>
          </td>
          <td>
          </td>
        
          <td>
            <strong>Total:</strong>
          </td>
          <td>
            <strong><%= number_to_currency(plan.total) %></strong>

          </td>

      </tbody>
    </table>
          <td>
          
          </td>
            <td><%= plan.email %></td>
          <td class="actions">
            <%= link_to icon_tag("eye-open"), plan_path(plan, format: "pdf"), rel: 'tooltip', title: 'Show', target: :_blank %>
          </td>
        </tr>
      <% end %>
      </tbody>
    </table>
    <%= will_paginate @plans %>
  </div><!-- /.sheet-inner -->
</div><!-- /.sheet -->

app/views/plans/new.html.erb
<% @title = "New plan" %>

<%= render 'form' %>

app/views/plans/show.html.erb
<% @title = "Showing plan" %>

<div class="form-horizontal">
  <div class="control-group">
    <label class="control-label">Name</label>
    <div class="controls">
      <span class="uneditable-input span6"><%= @plan.name %></span>
    </div>
  </div>
  
  <div class="form-actions">
    <%= link_to icon_tag("pencil") + ' Edit', edit_plan_path(@plan), class: 'btn btn-primary' %>
    <%= link_to 'Back', plans_path, class: 'btn' %>
  </div>
</div>