config/routes.rb
BuildingTrades::Application.routes.draw do
  

  devise_for :users, :skip => [:registrations] 
  resources :managers, only: [:index, :show]
  resources :custodians, only: [:index, :show]
  resources :companies, only: [:index, :show]
  resources :consultants, only: [:index, :show]
  resources :trades, only: [:index, :show]
  resources :plans, only: [:index, :show] do
    resources :contacts
  end


  devise_scope :user do
    root to: 'trades#index'
    #root to: 'passthrough#index' 
  end

  unauthenticated do
    root to: "sessions#new", :as => "unauthenticated"
  end

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities
  end
end

app/models/account.rb
class Account < ActiveRecord::Base
	belongs_to :plan
	belongs_to :manager
	has_many :securities


	def total
		total = self.sum(:market_value)
	end

	def self.active
		where(active: true).order("year desc")
	end

end

app/models/asset_class.rb
class AssetClass < ActiveRecord::Base
end

app/models/company.rb
class Company < ActiveRecord::Base
	has_many :securities
	has_many :plans, through: :securities
	validates :cusip, uniqueness: true

	def self.search(query)
  		where("name ilike ?", "%#{query}%") 
	end


end

app/models/consultant.rb
class Consultant < ActiveRecord::Base
	has_many :plans

	def self.search(query)
  		where("name ilike ?", "%#{query}%") 
	end

end

app/models/custodian.rb
class Custodian < ActiveRecord::Base
	has_many :plans

	def self.search(query)
  		where("name ilike ?", "%#{query}%") 
	end

end

app/models/manager.rb
class Manager < ActiveRecord::Base
	has_many :accounts
	has_one :plan, through: :accounts
	has_many :asset_classes, through: :accounts

	def self.search(query)
  		where("man_name ilike ?", "%#{query}%") 
	end

	def total
		total = self.accounts.sum(:market_value)
	end

	def self.asset_class_find(asset_class_id)
		includes(:accounts).where('accounts.asset_class_id = ?', asset_class_id)
	end

end

app/models/plan.rb
class Plan < ActiveRecord::Base
	has_many :accounts


	def self.search(query)
  		where("name ilike ?", "%#{query}%") 
	end

	def total
		total = self.accounts.sum(:market_value)
	end


end

app/models/security.rb
class Security < ActiveRecord::Base
	belongs_to :account
	belongs_to :company

	def self.current
		where(current: true)
	end
end

app/models/trade.rb
class Trade < ActiveRecord::Base
	has_many :plans

	def self.search(query)
  		where("name ilike ?", "%#{query}%") 
	end

	def total
		total = self.plans.sum(:total)
	end

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

	ROLES = %i[admin all smw iw ibew ubc ua]

	def roles=(roles)
	  roles = [*roles].map { |r| r.to_sym }
	  self.roles_mask = (roles & ROLES).map { |r| 2**ROLES.index(r) }.inject(0, :+)
	end

	def roles
	  ROLES.reject do |r|
	    ((roles_mask.to_i || 0) & 2**ROLES.index(r)).zero?
	  end
	end

	def has_role?(role)
	  roles.include?(role)
	end
end

app/helpers/accounts_helper.rb
module AccountsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
  def app_name
    "Building Trades Investment Tracker"
  end
end

app/helpers/companies_helper.rb
module CompaniesHelper
end

app/helpers/consultants_helper.rb
module ConsultantsHelper
end

app/helpers/custodians_helper.rb
module CustodiansHelper
end

app/helpers/managers_helper.rb
module ManagersHelper
end

app/helpers/plans_helper.rb
module PlansHelper
end

app/helpers/securities_helper.rb
module SecuritiesHelper
end

app/helpers/trades_helper.rb
module TradesHelper
end

app/views/layouts/_base.html.erb
<!DOCTYPE html>
<%= html_tag :lang => "en" do %>
  <head>
    <meta charset="utf-8">
    <title><%= [@title, app_name].compact.join(" - ") %></title>
    <%= csrf_meta_tags %>
    
    <!-- Ensure devices display responsive pages properly -->
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="http://html5shim.googlecode.com/svn/trunk/html5.js" type="text/javascript"></script>
    <![endif]-->

    <!-- Le fonts -->
    <%= stylesheet_link_tag "http://fonts.googleapis.com/css?family=Droid+Sans:400,700" %>

    <!-- Le styles -->
    <%= stylesheet_link_tag "application", :media => "all" %>
    <%= yield :styles %>

    <!-- Le fav and touch icons -->
    <%= favicon_link_tag %>
    <%# favicon_link_tag "apple-touch-icon.png", :rel => "apple-touch-icon" %>
    
    <%= yield :head %>
  </head>
  <body>
    <header>
      <%= render "layouts/navbar" %>
      <%= yield :header %>
      <hr />
    </header>
    
    <%= yield :banner %>

    <div id="main">
      <div class="container">
        <%= render "layouts/flashes" %>

        <%= yield %>
      </div> <!-- /.container -->
    </div> <!-- /#main -->
    
    <%= render "layouts/footer" %>

    <!-- Le javascript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <%= javascript_include_tag "application" %>
    <%= yield :javascript %>

  </body>
<% end %>

app/views/layouts/_flashes.html.erb
<% if alert %>
  <div class="alert alert-error">
    <a class="close" data-dismiss="alert">&times;</a>
    <%= icon_tag "remove" %> <%= alert %>
  </div>
<% end %>

<% if notice %>
  <div class="alert alert-warning">
    <a class="close" data-dismiss="alert">&times;</a>
    <%= icon_tag "info-sign" %> <%= notice %>
  </div>
<% end %>

app/views/layouts/_footer.html.erb
<footer>
  <div class="container">
  
    <p>&copy; <%= Date.today.year %> <%= app_name %>. All rights reserved.</p>
    
  </div> <!-- /.container -->
</footer>

app/views/layouts/_navbar.html.erb
<%# Top navigation bar containing the main menu of your app. %>
<div class="navbar navbar-fixed-top">
  <!-- TIP: to unfix the navbar:
    1. remove the 'navbar-fixed-top' class here and
    2. add the 'static-navbar' class to your body tag. -->
  <div class="navbar-inner">
    <div class="container">

      <!-- .btn-navbar is used as the toggle for collapsed navbar content -->
      <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </a>

      <!-- Le logo -->
      <a class="brand" href="<%= plans_path %>"><strong><%= app_name %></strong></a>

      <!-- Everything you want hidden at 940px or less, place within here -->
      <% if user_signed_in? %>
        <div class="nav-collapse">
            <ul class="nav">
              <%= activatable_li_tag_with_link 'Trades', trades_path %> 
            </ul>
          <ul class="nav">
          <%= activatable_li_tag_with_link 'Plans', plans_path %> 
         </ul>
         <ul class="nav">
          <%= activatable_li_tag_with_link 'Managers', managers_path %> 
         </ul>
         <ul class="nav">
          <%= activatable_li_tag_with_link 'Securities', companies_path %> 
         </ul>
         <ul class="nav">
          <%= activatable_li_tag_with_link 'Custodians', custodians_path%> 
         </ul>
         <ul class="nav">
          <%= activatable_li_tag_with_link 'Consultants', consultants_path%> 
         </ul>
         
          <%= yield :navbar %>
        </div> <!-- /.nav-collapse -->
        <% end %>
    </div> <!-- /.container -->
  </div> <!-- /.navbar-inner -->
</div> <!-- /.navbar -->

app/views/layouts/_user_nav.html.erb
<%# Links for current user. %>
<div class="navbar-text pull-right">
<% if user_signed_in? %>
  <%= icon_tag "user" %> Welcome, <strong><%= current_user.name %></strong> 
  <span class="divider">|</span>
  
    <ul class="nav">
      <%= link_to('Logout', destroy_user_session_path, :method => :delete) %> 
   </ul>
  <% else %>
    <ul class="nav">
      <%= activatable_li_tag_with_link 'Login', new_user_session_path  %>  
    </ul>
  <% end %>

</div>

app/views/layouts/application.html.erb
<% content_for :navbar, render("layouts/user_nav") %>

<%= render :layout => "layouts/base" do %>
  <div class="page-header">
    <div class="row">
      <div class="span7">
        <h2><%= @title %></h2>
        <%= yield :description %>
      </div>
      <div class="span2">
        <%= yield :actions %>
      </div>
    </div>
  </div><!-- /.page-header -->

  <div class="row">
    <div id="content" class="span9">
      <%= yield %>            
    </div> <!-- /#content -->

    
  </div> <!-- /.row -->
<% end %>

app/views/layouts/home.html.erb
<% content_for :navbar do %>
  <%= form_tag "?", :class => "navbar-search pull-right" do %>
    <%= text_field_tag :query, params[:query], :class => "search-query" %>
  <% end %>
<% end %>

<%= render :layout => "layouts/base" do %>
  <%= yield %>
<% end %>